model_provider = "sub2api"
model = "gpt-5.5"
disable_response_storage = true
plan_mode_reasoning_effort = "high"

[model_providers.ucloud]
name = "ucloud"
base_url = "https://api.modelverse.cn/v1"
wire_api = "responses"

[model_providers.v3]
name = "v3"
base_url = "https://jp.gpt.ge/v1"
wire_api = "responses"

[model_providers.jdy]
name = "jdy"
base_url = "https://jdytoken.cn/v1"
wire_api = "responses"

[model_providers.sub2api]
name = "sub2api"
base_url = "https://sub2api.llmapp.org"
wire_api = "responses"
